baseURL = "https://luo-luo.xyz/"
languageCode = "zh-cn"
title = "伤心树叶"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Curie"
  description = "Korea"
  github = "curie52"
  # facebook = "Example"
  # twitter = "Example"
  # linkedin = "Example"
  # instagram = "Example"
  # tumblr = "Example"
  email = "haoxianghuang16@gmail.com"
  # url = "https://example.com/"
  keywords = "blog, curie, korea"
  rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/avatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "Taiwan, China"
  userStatusEmoji = "😀"
  enableGitalk = false

  [params.gitalk]
    clientID = "Your client ID" # Your client ID
    clientSecret = "Your client secret" # Your client secret
    repo = "LuvSia" # 您的博客的github地址Repository name，例如：xxxx.github.io
    owner = "ventusoon" # 您的GitHub ID
    admin = "ventusoon" # 您的GitHub ID
    id = "location.pathname" # 文章页面的链接地址就是ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # 设置为true，如果是管理员登录，会自动创建issue，如果是false，需要管理员手动添加第一个评论(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # 可以自行添加反向代理
  
  [[params.links]]
    title = "curie52"
    href = "https://github.com/curie52"
  
  # [[params.links]]
  #   title = "Link2"
  #   href = "https://meik2333.com"
  #   icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

# [services]
#   [services.googleAnalytics]
#     ID = "UA-123456-789"
